package anonymous.oca.e2e;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import anonymous.oca.App;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.regex.Pattern;
import java.util.stream.*;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

/**
 * End-to-end regression test runner.
 *
 * <p>This suite executes only those cases that already have {@code input/} and {@code expected/}
 * directories present. For each case, it runs the pipeline in-process and compares normalized
 * outputs against the snapshots in {@code expected/registry.jsonl} and {@code
 * expected/outcomes.jsonl}.
 *
 * <p><strong>Environment requirements for deterministic replay</strong>
 *
 * <ul>
 *   <li>{@code DP_DISABLE_REAL_LLM} must be truthy (e.g., {@code 1}, {@code true})
 *   <li>{@code DP_LLM_CASSETTES} must point to a readable cassette directory (e.g., {@code
 *       src/test/cassettes})
 * </ul>
 *
 * <p><strong>Case layout</strong> under {@code src/test/resources/oca-pipeline/&lt;case&gt;}:
 *
 * <ul>
 *   <li>{@code input/} — Java sources root
 *   <li>{@code expected/} — {@code registry.jsonl}, {@code outcomes.jsonl}
 *   <li>{@code config.json} (optional) — {@code {"mainClass":"...","maxK":5}}
 * </ul>
 *
 * <p><strong>Creating or updating expected snapshots</strong><br>
 * The {@code expected/} folders are generated by the helper shell scripts {@code
 * scripts/record_one.sh} and {@code scripts/record_all.sh}, which run the pipeline with real LLM
 * calls (when {@code DP_DISABLE_REAL_LLM} is unset) and persist both registry and outcome files.
 * Once recorded, these expected snapshots can be replayed deterministically by this test.
 *
 * <p>Filter cases via {@code -Ddp.cases=caseA,caseB}.
 */
public class PipelineE2ETest {

  /** Root directory that contains all E2E cases. */
  private static final Path CASES_ROOT =
      Paths.get("").toAbsolutePath().resolve("src/test/resources/oca-pipeline");

  static {
    System.out.println("[E2E] CASES_ROOT=" + CASES_ROOT.toAbsolutePath());
  }

  private static final ObjectMapper M = new ObjectMapper();

  /**
   * Discovers runnable cases and produces one dynamic test per case.
   *
   * @return a stream of dynamic tests, one per discovered case
   * @throws IOException if listing or probing the cases directory fails
   */
  @TestFactory
  Stream<DynamicTest> runAllCases() throws IOException {
    assertTrue(Files.isDirectory(CASES_ROOT), "Missing cases root: " + CASES_ROOT);

    // --- Deterministic replay guards ---
    String disableReal =
        firstNonBlank(
            System.getProperty("DP_DISABLE_REAL_LLM"), System.getenv("DP_DISABLE_REAL_LLM"), "");
    assertTrue(
        isTruthy(disableReal),
        "DP_DISABLE_REAL_LLM must be truthy for deterministic replay.\n"
            + "Run via Gradle (./gradlew test) or set DP_DISABLE_REAL_LLM=1.");

    String casEnv =
        firstNonBlank(
            System.getProperty("DP_LLM_CASSETTES"), System.getenv("DP_LLM_CASSETTES"), "");
    assertFalse(
        casEnv.isBlank(),
        "DP_LLM_CASSETTES must be set to your cassette directory (e.g., src/test/cassettes).");

    Path cassetteDir = Paths.get(casEnv).toAbsolutePath().normalize();
    assertTrue(
        Files.isDirectory(cassetteDir) && Files.isReadable(cassetteDir),
        "DP_LLM_CASSETTES dir missing or unreadable: " + cassetteDir);

    final Set<String> onlyCases = parseCaseFilter(System.getProperty("dp.cases", "").trim());

    final List<Path> caseDirs;
    try (Stream<Path> s = Files.list(CASES_ROOT)) {
      caseDirs =
          s.filter(Files::isDirectory)
              .filter(PipelineE2ETest::hasInputAndExpected)
              .filter(p -> onlyCases.isEmpty() || onlyCases.contains(p.getFileName().toString()))
              .sorted(Comparator.comparing(p -> p.getFileName().toString()))
              .collect(Collectors.toList());
    }
    assertFalse(
        caseDirs.isEmpty(),
        "No runnable cases under: "
            + CASES_ROOT
            + (onlyCases.isEmpty() ? "" : " matching filter " + onlyCases));

    return caseDirs.stream()
        .map(
            dir ->
                DynamicTest.dynamicTest(dir.getFileName().toString(), () -> runCaseCompare(dir)));
  }

  // ---------- Small helpers (env parsing, filtering) ----------

  /**
   * Returns whether a string represents a truthy flag. Accepted values (case-insensitive): {@code
   * 1}, {@code true}, {@code yes}, {@code on}.
   *
   * @param v string to check (may be {@code null})
   * @return {@code true} if truthy; {@code false} otherwise
   */
  private static boolean isTruthy(String v) {
    if (v == null) return false;
    String t = v.trim().toLowerCase(Locale.ROOT);
    return t.equals("1") || t.equals("true") || t.equals("yes") || t.equals("on");
  }

  /**
   * Returns the first non-blank string from {@code a} or {@code b}, or {@code def} if both are
   * blank.
   *
   * @param a first candidate (may be {@code null})
   * @param b second candidate (may be {@code null})
   * @param def default value if both are blank
   * @return a non-blank string
   */
  private static String firstNonBlank(String a, String b, String def) {
    if (a != null && !a.isBlank()) return a;
    if (b != null && !b.isBlank()) return b;
    return def;
  }

  /**
   * Parses a comma-separated case filter into an ordered set.
   *
   * @param v comma-separated case names; blank means no filter
   * @return ordered set of case names to run
   */
  private static Set<String> parseCaseFilter(String v) {
    if (v.isBlank()) return Set.of();
    return Arrays.stream(v.split(","))
        .map(String::trim)
        .filter(s -> !s.isEmpty())
        .collect(Collectors.toCollection(LinkedHashSet::new));
  }

  /**
   * Checks whether a case directory has both {@code input/} and {@code expected/}.
   *
   * @param caseDir candidate case directory
   * @return {@code true} if runnable; {@code false} otherwise
   */
  private static boolean hasInputAndExpected(Path caseDir) {
    return Files.isDirectory(caseDir.resolve("input"))
        && Files.isDirectory(caseDir.resolve("expected"));
  }

  // ---------- Core compare logic ----------

  /**
   * Runs the pipeline for a given case and compares actual outputs with expected snapshots.
   *
   * <p>This method sets per-case system properties so the pipeline writes its registry and outcomes
   * into {@code build/e2e/&lt;case&gt;/}. Results are normalized (path/timestamp/UUID scrub + line
   * sort) prior to comparison.
   *
   * @param caseDir case directory containing {@code input/}, {@code expected/}, and optional {@code
   *     config.json}
   * @throws Exception if pipeline execution or comparison fails
   */
  private void runCaseCompare(Path caseDir) throws Exception {
    // Ensure deterministic replay (no real LLM)
    System.setProperty("DP_DISABLE_REAL_LLM", "1");

    Path inputDir = caseDir.resolve("input");
    Path expectedDir = caseDir.resolve("expected");
    Path expectedRegistry = expectedDir.resolve("registry.jsonl");
    Path expectedOutcomes = expectedDir.resolve("outcomes.jsonl");

    assertTrue(Files.isDirectory(inputDir), "Input dir missing: " + inputDir);
    assertTrue(Files.isDirectory(expectedDir), "Expected dir missing: " + expectedDir);
    assertTrue(Files.exists(expectedRegistry), "Missing expected file: " + expectedRegistry);

    // outcomes may be empty but typically present; allow empty when missing
    final boolean expectedOutcomesExists = Files.exists(expectedOutcomes);

    Path caseBuildDir = Paths.get("build", "e2e", caseDir.getFileName().toString());
    Files.createDirectories(caseBuildDir);
    Path buildRegistry = caseBuildDir.resolve("registry.jsonl");
    Path buildOutcomes = caseBuildDir.resolve("outcomes.jsonl");
    Files.deleteIfExists(buildRegistry);
    Files.deleteIfExists(buildOutcomes);

    CfgLite cfg = loadCfg(caseDir.resolve("config.json"));

    Map<String, String> prev = snapshotAndSetCaseProps(buildRegistry, buildOutcomes, cfg.dpProps);
    try {
      final List<String> args;
      if ("external".equals(cfg.execMode)) {
        assertFalse(cfg.command.isEmpty(), "External mode requires a non-empty command list");
        // Extract runner script name (last element of command, e.g. "run.sh" from
        // ["bash","run.sh"])
        String scriptName = cfg.command.get(cfg.command.size() - 1);
        args =
            List.of(
                "--external-project",
                "--project-root",
                inputDir.toString(),
                "--main-src",
                ".",
                "--runner-script",
                scriptName);
      } else {
        args = List.of(inputDir.toString(), "", cfg.mainClass, String.valueOf(cfg.maxK));
      }
      App.main(args.toArray(new String[0]));

      assertTrue(Files.exists(buildRegistry), "Pipeline produced no registry at " + buildRegistry);
      if (Files.notExists(buildOutcomes)) {
        Files.writeString(
            buildOutcomes,
            "",
            StandardCharsets.UTF_8,
            StandardOpenOption.CREATE,
            StandardOpenOption.TRUNCATE_EXISTING);
      }

      String actualRegistry = normalizeAndSort(slurp(buildRegistry));
      String actualOutcomes = normalizeAndSort(slurp(buildOutcomes));
      String expectedReg = normalizeAndSort(slurp(expectedRegistry));
      String expectedOut = normalizeAndSort(expectedOutcomesExists ? slurp(expectedOutcomes) : "");

      assertEquals(
          expectedReg, actualRegistry, () -> diffMsg("registry", expectedRegistry, buildRegistry));
      assertEquals(
          expectedOut, actualOutcomes, () -> diffMsg("outcomes", expectedOutcomes, buildOutcomes));
    } finally {
      restoreProps(prev);
    }
  }

  // ---------- File and normalization utilities ----------

  /**
   * Builds a friendly diff header when a comparison fails.
   *
   * @param kind logical artifact name (e.g., {@code "registry"} or {@code "outcomes"})
   * @param expected path to the expected snapshot
   * @param actual path to the actual build artifact
   * @return formatted message used by assertion failures
   */
  private static String diffMsg(String kind, Path expected, Path actual) {
    return "Normalized "
        + kind
        + " differs.\nExpected: "
        + expected.toAbsolutePath()
        + "\nActual:   "
        + actual.toAbsolutePath();
  }

  /**
   * Reads the entire file as a UTF-8 string.
   *
   * @param p path to read
   * @return file contents
   * @throws IOException if the file cannot be read
   */
  private static String slurp(Path p) throws IOException {
    return Files.readString(p, StandardCharsets.UTF_8);
  }

  /**
   * Normalizes volatile content so outputs are comparable across machines and times.
   *
   * <ul>
   *   <li>Normalizes line endings
   *   <li>Scrubs absolute paths and user home
   *   <li>Scrubs timestamped working directories and ISO timestamps
   *   <li>Scrubs UUIDs
   * </ul>
   *
   * @param s raw text
   * @return normalized text
   */
  private static String normalize(String s) {
    String out = s;

    // Normalize newlines
    out = out.replaceAll("\\R", "\n");

    // Absolute project path → <ABS>
    try {
      String abs = new File("").getAbsolutePath().replace("\\", "\\\\");
      out = out.replaceAll(Pattern.quote(abs), "<ABS>");
    } catch (Exception ignore) {
    }

    // HOME → <HOME>
    String home = System.getProperty("user.home");
    if (home != null && !home.isBlank()) {
      out = out.replaceAll(Pattern.quote(home.replace("\\", "\\\\")), "<HOME>");
    }

    // Timestamped workdir names: src-YYYYMMDD-HHMMSS → src-<TS>
    out = out.replaceAll("src-\\d{8}-\\d{6}", "src-<TS>");

    // UUIDs → <ID>
    out =
        out.replaceAll(
            "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}", "<ID>");

    // Temp subdir under build/oca_work
    out = out.replaceAll("build/oca_work/[^\\s\"']+", "build/oca_work/<TSDIR>");

    // createdAt timestamps (ISO-8601) → <TS>
    out = out.replaceAll("\"createdAt\"\\s*:\\s*\"[^\"]+\"", "\"createdAt\":\"<TS>\"");

    return out.trim();
  }

  /**
   * Normalizes then sorts lines to stabilize ordering when multiple writers run in parallel.
   *
   * @param s raw text
   * @return normalized, line-sorted text
   */
  private static String normalizeAndSort(String s) {
    String norm = normalize(s);
    String[] lines = norm.split("\n");
    List<String> keep = new ArrayList<>();
    for (String line : lines) {
      String t = line.trim();
      if (!t.isEmpty()) keep.add(t);
    }
    Collections.sort(keep);
    return String.join("\n", keep);
  }

  // ---------- Case config ----------

  /** Minimal per-case configuration. */
  private static final class CfgLite {
    /** Fully-qualified main class to execute (e.g., {@code com.example.Main}). */
    final String mainClass;

    /** Max K (domain-specific pipeline parameter). */
    final int maxK;

    /** Extra {@code dp.*} system properties from the {@code dp} section of config.json. */
    final Map<String, String> dpProps;

    /** Execution mode: {@code null} / {@code "native"} or {@code "external"}. */
    final String execMode;

    /** Command to run in external mode (e.g., {@code ["bash", "run.sh"]}). */
    final List<String> command;

    CfgLite(
        String mainClass,
        int maxK,
        Map<String, String> dpProps,
        String execMode,
        List<String> command) {
      this.mainClass = mainClass;
      this.maxK = maxK;
      this.dpProps = dpProps;
      this.execMode = execMode;
      this.command = command;
    }
  }

  private static final ObjectMapper OM = new ObjectMapper();

  /**
   * Loads per-case configuration from an optional JSON file.
   *
   * @param jsonPath path to {@code config.json}; missing file returns defaults
   * @return parsed configuration with sensible defaults
   * @throws IOException if the file exists but cannot be parsed
   */
  private static CfgLite loadCfg(Path jsonPath) throws IOException {
    String mainClass = "com.example.Main";
    int maxK = 5;
    Map<String, String> dpProps = new LinkedHashMap<>();
    String execMode = null;
    List<String> command = new ArrayList<>();
    if (Files.isRegularFile(jsonPath)) {
      JsonNode j = OM.readTree(jsonPath.toFile());
      if (j.hasNonNull("mainClass")) mainClass = j.get("mainClass").asText();
      if (j.hasNonNull("maxK")) maxK = j.get("maxK").asInt(5);
      if (j.hasNonNull("execMode")) execMode = j.get("execMode").asText();
      if (j.hasNonNull("command") && j.get("command").isArray()) {
        j.get("command").forEach(el -> command.add(el.asText()));
      }
      JsonNode dp = j.get("dp");
      if (dp != null && dp.isObject()) {
        dp.fields()
            .forEachRemaining(
                e -> {
                  JsonNode v = e.getValue();
                  if (v.isTextual()) {
                    dpProps.put(e.getKey(), v.asText());
                  } else if (v.isArray()) {
                    // Serialize array values as comma-separated strings
                    List<String> items = new ArrayList<>();
                    v.forEach(el -> items.add(el.asText()));
                    dpProps.put(e.getKey(), String.join(",", items));
                  } else {
                    dpProps.put(e.getKey(), v.asText());
                  }
                });
      }
    }
    return new CfgLite(mainClass, maxK, dpProps, execMode, command);
  }

  // ---------- System property scoping ----------

  /**
   * Sets per-case system properties and returns a snapshot of the previous values.
   *
   * <p>Each entry maps a key to its previous value, or {@code null} if the key was absent before
   * this call. Pass the result to {@link #restoreProps(Map)} in a finally block.
   *
   * @param buildRegistry destination path for the registry
   * @param buildOutcomes destination path for the outcomes
   * @param dpProps extra {@code dp.*} props from the case config's {@code dp} section
   * @return snapshot of all modified keys (null value = was absent)
   */
  private static Map<String, String> snapshotAndSetCaseProps(
      Path buildRegistry, Path buildOutcomes, Map<String, String> dpProps) {
    Map<String, String> prev = new LinkedHashMap<>();
    // Core props
    prev.put("dp.registry", System.getProperty("dp.registry"));
    prev.put("dp.outcomes", System.getProperty("dp.outcomes"));
    prev.put("dp.registryReset", System.getProperty("dp.registryReset"));
    for (String key : dpProps.keySet()) {
      prev.put("dp." + key, System.getProperty("dp." + key));
    }

    System.setProperty("dp.registry", buildRegistry.toAbsolutePath().toString());
    System.setProperty("dp.outcomes", buildOutcomes.toAbsolutePath().toString());
    System.setProperty("dp.registryReset", "true");
    for (Map.Entry<String, String> e : dpProps.entrySet()) {
      System.setProperty("dp." + e.getKey(), e.getValue());
    }
    return prev;
  }

  /**
   * Restores system properties to the state captured by {@link #snapshotAndSetCaseProps}.
   *
   * <p>A {@code null} value in the map means the key was absent before the test and is cleared.
   *
   * @param prev snapshot produced by {@link #snapshotAndSetCaseProps}
   */
  private static void restoreProps(Map<String, String> prev) {
    for (Map.Entry<String, String> e : prev.entrySet()) {
      if (e.getValue() != null) {
        System.setProperty(e.getKey(), e.getValue());
      } else {
        System.clearProperty(e.getKey());
      }
    }
  }
}
