package anonymous.oca.llm;

import com.openai.client.OpenAIClient;
import com.openai.client.okhttp.OpenAIOkHttpClient;
import com.openai.core.JsonSchemaLocalValidation;
import com.openai.models.ChatModel;
import com.openai.models.chat.completions.ChatCompletionCreateParams;
import com.openai.models.chat.completions.StructuredChatCompletion;
import com.openai.models.chat.completions.StructuredChatCompletionCreateParams;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * Real LLM client that uses the official OpenAI Java SDK to perform live completions.
 *
 * <p>This implementation connects to OpenAI’s API (via {@link OpenAIOkHttpClient#fromEnv()}) and
 * requests structured completions conforming to the JSON schema defined by {@link
 * LlmInvariantGenerator.InvariantsOut}. The response is automatically validated and deserialized
 * into invariant items.
 *
 * <p>This class is used for <em>recording mode</em>, where actual model responses are fetched and
 * saved as cassettes for later deterministic replay.
 *
 * @see LlmInvariantGenerator
 * @see ReplayingLlmClient
 */
public final class RealOpenAILlmClient implements LlmClient {
  private final OpenAIClient client;
  private final ChatModel model;

  /**
   * Creates a new OpenAI-based LLM client using environment credentials.
   *
   * @param model the chat model (e.g., {@code ChatModel.GPT_4O}) to use for completions
   */
  public RealOpenAILlmClient(ChatModel model) {
    this.client = OpenAIOkHttpClient.fromEnv();
    this.model = Objects.requireNonNull(model);
  }

  /**
   * Sends a prompt pair (system + user) to the OpenAI API and returns structured invariant items
   * parsed from the model’s JSON response.
   *
   * @param system the system prompt defining model behavior or constraints
   * @param user the user prompt containing the input or code under analysis
   * @return list of invariant items generated by the model
   * @throws IOException if network communication or schema validation fails
   */
  @Override
  public List<LlmInvariantGenerator.InvariantsOut.Item> complete(String system, String user)
      throws IOException {
    StructuredChatCompletionCreateParams<LlmInvariantGenerator.InvariantsOut> params =
        ChatCompletionCreateParams.builder()
            .model(model)
            .responseFormat(
                LlmInvariantGenerator.InvariantsOut.class, JsonSchemaLocalValidation.YES)
            .addSystemMessage(system)
            .addUserMessage(user)
            .build();

    StructuredChatCompletion<LlmInvariantGenerator.InvariantsOut> completion =
        client.chat().completions().create(params);

    return completion.choices().stream()
        .flatMap(c -> c.message().content().stream())
        .filter(java.util.Objects::nonNull)
        .flatMap(out -> out.invariants.stream())
        .filter(java.util.Objects::nonNull)
        .collect(Collectors.toList());
  }
}
